### PR TITLE
ENG-5930 react banner mrec transition bug

### PR DESCRIPTION
**Pull request by kkawai**
**[Jira Ticket Link](#) | Release Version**
https://freestar.atlassian.net/browse/ENG-5930

## Description, Motivation and Context
Fixed react native bug when user shows small banner on first screen, then shows mrec banner on the next screen, comes back to first screen.  user sees small banner resized to mrec size box.  only occures in react native due to the way it's re-using views.

**What is the goal of ticket?  What are the acceptance criteria?**

**What are the changes?**

**Why did you choose this solution?**

## Checklist:
[ ] Unit tests are all passing on local.

[ ] I unit tested new functionality.

### CODE REVIEW

**Comment by vjfreestar** [comment]
@kkawai this is not an hotfix right? i see the PR is to master.

**Comment by kkawai** [comment]
> @kkawai this is not an hotfix right? i see the PR is to master.

It kind of was a hotfix I just forgot to name the branch as a hotfix branch @vjfreestar

**Review by vjfreestar — CHANGES_REQUESTED** [review]
@kkawai  https://freestar.slack.com/files/U019LT1TCMT/F01NSQDCSAK/image_from_ios.jpg please follow this and create a hot fix branch and move the target of this PR to hot-ifx, please follow the naming convention hot-fix-<current release + increment the patch version) assuming this is a hot-fix rather than feature request.

**Comment by kkawai** [comment]
duplicate

**Comment by kkawai** [comment]
https://github.com/freestarcapital/freestar-plugin-react-native/pull/8

**Pull request closed without merging**
